package com.hiretaxi.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.hiretaxi.model.ImageBanner;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "IMAGE_BANNER".
*/
public class ImageBannerDao extends AbstractDao<ImageBanner, Long> {

    public static final String TABLENAME = "IMAGE_BANNER";

    /**
     * Properties of entity ImageBanner.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property SrcUrl = new Property(2, String.class, "srcUrl", false, "SRC_URL");
        public final static Property ImgCacheUrl = new Property(3, String.class, "imgCacheUrl", false, "IMG_CACHE_URL");
    }


    public ImageBannerDao(DaoConfig config) {
        super(config);
    }
    
    public ImageBannerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IMAGE_BANNER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"TITLE\" TEXT," + // 1: title
                "\"SRC_URL\" TEXT," + // 2: srcUrl
                "\"IMG_CACHE_URL\" TEXT);"); // 3: imgCacheUrl
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IMAGE_BANNER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ImageBanner entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String srcUrl = entity.getSrcUrl();
        if (srcUrl != null) {
            stmt.bindString(3, srcUrl);
        }
 
        String imgCacheUrl = entity.getImgCacheUrl();
        if (imgCacheUrl != null) {
            stmt.bindString(4, imgCacheUrl);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ImageBanner entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String srcUrl = entity.getSrcUrl();
        if (srcUrl != null) {
            stmt.bindString(3, srcUrl);
        }
 
        String imgCacheUrl = entity.getImgCacheUrl();
        if (imgCacheUrl != null) {
            stmt.bindString(4, imgCacheUrl);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ImageBanner readEntity(Cursor cursor, int offset) {
        ImageBanner entity = new ImageBanner( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // srcUrl
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // imgCacheUrl
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ImageBanner entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSrcUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setImgCacheUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ImageBanner entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ImageBanner entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ImageBanner entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
